Test/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls import url

from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('blog/', include('blog.urls')),


]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

blog/urls.py
from django.urls import path

from .import views

app_name='blog'
urlpatterns = [

    path('', views.index, name='index'),
    path('posts/<id>', views.show, name='show'),

]

blog/models.py
from django.db import models

# Create your models here.
class TimespamtedModel(models.Model):

	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		abstract = True

class Post(TimespamtedModel):
	title = models.CharField(max_length=255)
	body = models.TextField()



	def __str__(self):
		return self.title

Test/views.py
from django.shortcuts import render

def home(request):
	return render(request, 'pages/home.html')

def about(request):
	return render(request, 'pages/about.html')

def contact(request):
	return render(request, 'pages/contact.html') 

blog/views.py
from django.shortcuts import render, get_object_or_404
#from .mocks import Post
from .models import Post
from django.http import Http404

# Create your views here.


def index(request):
	posts = Post.objects.all()
	return render(request, 'blog/index.html' , {'posts' : posts})

def show(request, id):
	posts = get_object_or_404(Post, pk=id)
	#try:
	#	posts = Post.objects.get(pk=id)
	#	return render(request, 'blog/show.html', {'posts' : posts})

	#except Post.DoesNotExist:
	#	raise Http404('Sorry the post #{} was not found'.format(id))
	
	return render(request, 'blog/show.html', {'posts' : posts})

blog/templates/blog/base.html
{% extends 'layout/base.html' %}

{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/styles.css' %}">
{% endblock %}

{% block content %}
	<h1>Blog</h1>

	{% block body %}{% endblock %}
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}


{% block title %}Blog{% endblock %}

{% block body %}

	<h1>Blog ({{ posts|length }} posts)</h1>


	{% for posts in posts %}

		<article>

			<h2><a href="{% url 'blog:show' posts.id %}"> # {{ posts.id }} - {{ posts.title|upper }} </a> </h2>
			<p> {{ posts.body|truncatewords:3 }} </p>
			<p> <a href="{% url 'blog:show' posts.id %}"> lire la suite </a> </p>
		</article>

		{% if not forloop.last %}
		<hr>
		{% endif %}
	{% empty %}
		<p> no post available </p>

	{% endfor %}

{% endblock  %}

blog/templates/blog/show.html
{% extends 'blog/base.html' %}

{% block title %}Blog | {{ posts.title }}{% endblock %}

{% block body %}

	<article>
		<h1> show post details #{{posts.id}}  alala</h1>
		<p>{{posts.body}}</p>
	</article>
	<hr>
	<p><a href="{% url 'blog:index' %}">All posts</a>

{% endblock  %}

templates/layout/_footer.html
<footer class="footer">
	<p>&copy; Copyright &middot; {% now 'Y' %} Adrien &middot; All right reserved!</p>
</footer>

templates/layout/_nav.html
<nav class="navbar">

	<div class="wrapper">

		<a href="{% url 'home' %}" class="navbar-brand"> Test </a>

		<ul class="navbar-right">
			<li> <a href="{% url 'home' %}"> Home </a> </li>
			<li> <a href="{% url 'blog:index' %}"> Blog </a> </li>
			<li> <a href="{% url 'about' %}"> About </a> </li>
			<li> <a href="{% url 'contact' %}"> contact </a> </li>
		</ul>

	</div>

</nav>

templates/layout/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>{% block title %}Test{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css">

	<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

	{% block stylesheets %}{% endblock %}
</head>

<body>

	{% include 'layout/_nav.html' %}

	<div class="wrapper">
		{% block content %}{% endblock %}
	</div>

	{% include 'layout/_footer.html' %}

	{% block javascripts %}{% endblock %}
	
</body>
</html>

templates/pages/about.html
{% extends 'layout/base.html' %}

{% block title %}about{% endblock %}

{% block content %}
	<h1> about </h1>
{% endblock %}

templates/pages/contact.html
{% extends 'layout/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
	<h1> Contact </h1>
{% endblock %}

templates/pages/home.html
{% extends 'layout/base.html' %}

{% block title %}Homepage{% endblock %}

{% block content %}

	<h1>Hello</h1>

	<p><a href="{% url 'blog:index' %}"> Visiter le blog </a></p>

{% endblock %}